### ISSUE TITLE
Wallet adapter (Phantom) does not connect for some users

### ISSUE THREAD

**Issue by eeebad** [anza-xyz/wallet-adapter#856] opened 2023-12-05 12:45 UTC
Describe the bug

I've encountered reports from multiple users who are experiencing difficulty connecting their wallets. While I haven't been able to reproduce the issue personally, some users mention that after selecting a wallet from the modal listing available options, nothing further occurs – it seems the extension popup fails to appear.

Desktop:

Browser [e.g. chrome, firefox, safari]

**Comment by jordaaash** [comment] 2023-12-05 17:25
Duplicate of https://github.com/solana-labs/wallet-adapter/pull/836 and https://github.com/solana-labs/wallet-adapter/issues/852.

Already addressed by https://github.com/solana-labs/wallet-adapter/issues/853#issuecomment-1839221212.

The bug report template is there for a reason. If we can't replicate the issue, we can't do anything about it.

Please do not open any more issues about this.

**Closed as completed by jordaaash** 2023-12-05 17:25 UTC
