### ISSUE TITLE
Issue in updating values on switching between phantom accounts

### ISSUE THREAD

**Issue by aminlatifi** [anza-xyz/wallet-adapter#883] opened 2024-01-15 12:45 UTC
None of the values returned by the useWallet hook (e.g. publicKey, connecting, connected, ...) don't change when the user switches to another connected phantom account. The user needs to refresh the page to see updated values. Technically the hook state values don't change I guess.

It's reported here with a fancy video: https://github.com/Giveth/giveth-dapps-v2/issues/3400#issuecomment-1887383061

We have used `@solana/wallet-adapter-react`, but it's repeatable on a project built with Sevelte 
https://github.com/dmdin/donation-platform
https://soldons.vercel.app/

**Expected behavior**
Update hook state values by changing the wallet.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave

**Additional context**
Similar to https://github.com/solana-labs/wallet-adapter/issues/747

**Comment by aminlatifi** [comment] 2024-01-17 13:34
Any update?

**Comment by jordaaash** [comment] 2024-01-17 19:48
cc @bfriel (I'll DM you to try to locate where this is happening)

**Comment by 0xproflupin** [comment] 2024-01-25 11:30
@jordaaash @aminlatifi Will dive deeper into this but can't reproduce on any dapp I visit, including our sandbox: https://phantom-sandboxes.vercel.app/sol-adapter-sandbox, which uses the same `useWallet` hook.


https://github.com/solana-labs/wallet-adapter/assets/23377962/7fc09428-6a74-4dcb-8a92-9902ff9469a0

**Comment by aminlatifi** [comment] 2024-01-25 11:43
@0xproflupin Is this its repo? https://github.com/phantom/sandbox/blob/main/src/App.tsx
If yes, they haven't use hook and have handled events manually.

**Comment by mcintyre94** [comment] 2024-01-25 12:03
FWIW I can repro on https://soldons.vercel.app/ (and not on Phantom's sol-adapter-sandbox)

**Comment by 0xproflupin** [comment] 2024-01-25 12:15
@aminlatifi this is the repo: https://github.com/0xproflupin/phantom-sandboxes/blob/main/src/sandboxes/adapter-sandbox/App.tsx
As Callum said, if you could share source for https://soldons.vercel.app/, that would be helpful

**Comment by aminlatifi** [comment] 2024-01-25 12:19
> @aminlatifi this is the repo: https://github.com/0xproflupin/phantom-sandboxes/blob/main/src/sandboxes/adapter-sandbox/App.tsx As Callum said, if you could share source for https://soldons.vercel.app/, that would be helpful

It's soldons source code
https://github.com/dmdin/donation-platform

**Comment by mcintyre94** [comment] 2024-01-25 12:38
> We have used @solana/wallet-adapter-react, but it's repeatable on a project built with Sevelte

Could you share the code using `@solana/wallet-adapter-react`? We can then try to debug it against the source code Anvit shared and try to figure out why it's not working/if there's a bug somewhere that needs fixing. Or we'll be able to figure out what in Anvit's code you can use to make it work.

I don't have any experience with Svelte or a working Svelte example to debug against, so I don't think we're going to get any  further with the SolDons example currently.

FWIW as one other data point, I can repro with Solflare (but not Phantom) on https://phantom-sandboxes.vercel.app/sol-adapter-sandbox

**Comment by aminlatifi** [comment] 2024-01-25 12:41
Our own repo is this, https://github.com/giveth/giveth-dapps-v2/
But we have handled the phantom manually by extracting phantom provider and listening to appropriate events.

**Comment by mcintyre94** [comment] 2024-01-25 13:10
To be honest I think we're going to need a minimal app (eg a fork of Phantom's sol-adapter-sandbox) that shows this issue. There's nothing I can see in the Phantom sandbox code that seems to be working around an issue here.

**Comment by jordaaash** [comment] 2024-02-11 15:00
Closing because we can't repro in our code. Check out the starter projects in this repo or https://github.com/solana-labs/dapp-scaffold to see correct config examples for Wallet Adapter.

**Closed by jordaaash** 2024-02-11 15:00 UTC

**Comment by yornaath** [comment] 2024-04-15 10:29
A litle update. I ran into the same issue for phantom when running it in a nextjs app in dev mode, using the wallet multi button the account wouldnt change when I changed my account in the phantom extension.

But when building the next app using `npm run build` and then starting it using `npm run start` it worked fine.
So I think its a problem with nextjs hot reloading, or hot reloading in general.

**Comment by Haseebshah936** [comment] 2024-05-21 16:46
@yornaath Thanks man helped alot.

**Comment by Haseebshah936** [comment] 2024-05-21 16:47
> A litle update. I ran into the same issue for phantom when running it in a nextjs app in dev mode using `npm run dev`, using the wallet multi button the account wouldnt change when I changed my account in the phantom extension.
> 
> But when building the next app using `npm run build` and then starting it using `npm run start` it worked fine. So I think its a problem with nextjs hot reloading, or hot reloading in general.

Worked for me thanks bud.

**Comment by GiovaniGuizzoYUB** [comment] 2024-08-22 18:26
> A litle update. I ran into the same issue for phantom when running it in a nextjs app in dev mode using `npm run dev`, using the wallet multi button the account wouldnt change when I changed my account in the phantom extension.
> 
> But when building the next app using `npm run build` and then starting it using `npm run start` it worked fine. So I think its a problem with nextjs hot reloading, or hot reloading in general.

I can confirm. I am having the same issue. Starting the built server seems to fix the problem. Dev won't change the wallet.

**Comment by 0x3r0x** [comment] 2024-12-10 20:55
I had the same issue, especially with phantom wallet and tried everything. HTTPS didn't fix it, production (npm run build + npm start) didn't fix it.. I used ngrok to tunnel the app from http://localhost:3000 to a publicly reachable domain and voilá it worked (still in dev mode).. spent like 6 hours trying to debug it and thought something was wrong with my code.. like always :D hope this helps someone, cheers

**Comment by AxyLm** [comment] 2025-01-05 04:32
I also encountered this problem

https://github.com/anza-xyz/wallet-adapter/issues/1042

**Comment by AxyLm** [comment] 2025-01-05 04:34
> To be honest I think we're going to need a minimal app (eg a fork of Phantom's sol-adapter-sandbox) that shows this issue. There's nothing I can see in the Phantom sandbox code that seems to be working around an issue here.老实说，我认为我们需要一个显示此问题的最小应用程序（例如 Phantom 的 sol-adapter-sandbox 的分支）。我在 Phantom 沙盒代码中没有看到任何内容似乎可以解决此处的问题。

https://github.com/anza-xyz/wallet-adapter/issues/1042

**Comment by 0x3r0x** [comment] 2025-01-05 05:50
> I also encountered this problem
> 
> 
> 
> https://github.com/anza-xyz/wallet-adapter/issues/1042
> 
> 
> 
> https://github.com/AxyLm/react-solana

Try using ngrok, that solved it for me...
Read my previous post.. hope it helps..

**Comment by AxyLm** [comment] 2025-01-07 17:09
> > I also encountered this problem
> > #1042
> > [AxyLm/react-solana](https://github.com/AxyLm/react-solana)
> 
> Try using ngrok, that solved it for me... Read my previous post.. hope it helps..

It doesn't work

**Comment by frantic69420** [comment] 2025-03-06 20:45
I got into this issue jrecentry, using nextjs on mac os, and the thing is that couple months ago at the same pc with same setup everything worked, also I checked that on jup.ag account switch also stopped working, so i think there is an issue with recent updates or compatibility issues

**Comment by viraj-kokane** [comment] 2025-03-11 20:59
> I got into this issue recently, using nextjs on mac os, and the thing is that couple months ago at the same pc with same setup everything worked, also I checked that on jup.ag account switch also stopped working, so i think there is an issue with recent updates or compatibility issues

I encountered the same issue today on both my dApp (using NextJS 15 and @solana/wallet-adapter-react) and the jup.ag website. Initially, I thought it was a problem with my configuration, but after testing, I realized that account switching isn't working on jup.ag either. useWallet does not detect the new wallet after changing. When it does work, it works on both platforms.

**Comment by liho00** [comment] 2025-07-19 05:40
same issue
