### ISSUE TITLE
Module not found: Can't resolve '@ngraveio/bc-ur'

### ISSUE THREAD

**Issue by rlisac** [anza-xyz/wallet-adapter#909] opened 2024-03-01 14:30 UTC
hello everyone

I am currently developing a new page and have recently received the following error message:

./node_modules/.pnpm/@keystonehq+bc-ur-registry@0.5.5/node_modules/@keystonehq/bc-ur-registry/dist/Decoder/index.js:4:16
Module not found: Can't resolve '@ngraveio/bc-ur'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/@keystonehq+bc-ur-registry@0.5.5/node_modules/@keystonehq/bc-ur-registry/dist/index.js
./node_modules/.pnpm/@keystonehq+sol-keyring@0.3.1/node_modules/@keystonehq/sol-keyring/dist/sol-keyring.cjs.development.js
./node_modules/.pnpm/@keystonehq+sol-keyring@0.3.1/node_modules/@keystonehq/sol-keyring/dist/index.js
./node_modules/.pnpm/@solana+wallet-adapter-keystone@0.1.12_@solana+web3.js@1.90.0/node_modules/@solana/wallet-adapter-keystone/lib/esm/adapter.js
./node_modules/.pnpm/@solana+wallet-adapter-keystone@0.1.12_@solana+web3.js@1.90.0/node_modules/@solana/wallet-adapter-keystone/lib/esm/index.js
./node_modules/.pnpm/@solana+wallet-adapter-wallets@0.19.27_@babel+runtime@7.24.0_@solana+web3.js@1.90.0_bs58@4.0._ippf7guhaaiva42ay32utmn2hy/node_modules/@solana/wallet-adapter-wallets/lib/esm/index.js
./components/ConnectWallet.jsx
./components/Header.js

Do you have any idea why this could be?

<img width="609" alt="Bildschirmfoto 2024-03-01 um 15 36 16" src="https://github.com/anza-xyz/wallet-adapter/assets/12280821/12eddd04-3a1d-48a1-8d82-e2a5c39f8415">

Thank you very much for a short feedback.

**Comment by ChetanXpro** [comment] 2024-03-01 16:56
I'm facing the same bug. Everything was working fine, but today, suddenly, I encountered this bug.

**Comment by mcintyre94** [comment] 2024-03-01 17:36
Hmm I'm not able to reproduce this. I created a new project and ran:

```sh
$ npm install --save \
    @solana/wallet-adapter-base \
    @solana/wallet-adapter-react \
    @solana/wallet-adapter-react-ui \
    @solana/wallet-adapter-wallets \
    @solana/web3.js \
    react
```

And all installed with no errors.

This `@ngrave-io/bc-ur` package is included in those dependencies:
```sh
$ grep 'bc-ur' package-lock.json
    "node_modules/@keystonehq/bc-ur-registry": {
      "resolved": "https://registry.npmjs.org/@keystonehq/bc-ur-registry/-/bc-ur-registry-0.5.5.tgz",
        "@ngraveio/bc-ur": "^1.1.5",
    "node_modules/@keystonehq/bc-ur-registry-sol": {
      "resolved": "https://registry.npmjs.org/@keystonehq/bc-ur-registry-sol/-/bc-ur-registry-sol-0.3.1.tgz",
        "@keystonehq/bc-ur-registry": "^0.5.0",
        "@ngraveio/bc-ur": "^1.0.0",
        "@keystonehq/bc-ur-registry": "^0.5.0",
        "@keystonehq/bc-ur-registry-sol": "^0.3.1",
    "node_modules/@ngraveio/bc-ur": {
      "resolved": "https://registry.npmjs.org/@ngraveio/bc-ur/-/bc-ur-1.1.9.tgz",
```

Also `npm install @ngraveio/bc-ur` works in a new project

There were new versions of `bc-ur` published 16 and 11 hours ago, and the version before that was 3 years ago. So the issue could be coming from that new version.

Is anyone able to provide repro steps for this so I can take a closer look?

**Comment by ChetanXpro** [comment] 2024-03-01 17:40
@mcintyre94 can you please try to use these library like this, and try to build your  Nextjs project,These  library are not creating any problem while installing.

```
"use client";

import React from "react";
import Header from "../Header";

import {
  ConnectionProvider,
  WalletProvider,
} from "@solana/wallet-adapter-react";
import { useMemo } from "react";
import {
  CloverWalletAdapter,
  PhantomWalletAdapter,
  SolflareWalletAdapter,
  MathWalletAdapter,
} from "@solana/wallet-adapter-wallets";
import { clusterApiUrl } from "@solana/web3.js";

const Sites = ({ children }: any) => {
  const wallets = useMemo(() => [new PhantomWalletAdapter()], []);

  const endpoint = useMemo(() => clusterApiUrl("mainnet-beta"), []);

  return (
    <ConnectionProvider endpoint={endpoint}>
      <WalletProvider wallets={wallets} autoConnect>
        <div className="">
          <Header />
          {children}
        </div>
      </WalletProvider>
    </ConnectionProvider>
  );
};

export default Sites;

```

**Comment by mcintyre94** [comment] 2024-03-01 18:00
Thanks @ChetanXpro, I've got a repro on stackblitz now: https://stackblitz.com/edit/nextjs-pksjhy?file=app%2Flayout.tsx

**Comment by ChetanXpro** [comment] 2024-03-01 18:07
> Thanks @ChetanXpro, I've got a repro on stackblitz now: https://stackblitz.com/edit/nextjs-pksjhy?file=app%2Flayout.tsx

Perfect , i think this issue might help you.
https://github.com/ngraveio/bc-ur/issues/21

**Comment by mcintyre94** [comment] 2024-03-01 18:15
Hmm that seems to have been before 1.1.9 was merged and we're still seeing the issue

**Comment by ChetanXpro** [comment] 2024-03-01 18:30
> Hmm that seems to have been before 1.1.9 was merged and we're still seeing the issue

For now i have used "@solana/wallet-adapter-backpack" to get BackpackWalletAdapter, this one is working fine , but its deprecated , so in future i will use @solana/wallet-adapter-wallets

**Comment by mcintyre94** [comment] 2024-03-01 18:39
Okay so it looks like this is an issue with the latest version of `@ngraveio/bc-ur`: https://github.com/ngraveio/bc-ur/issues/21#issuecomment-1973717698

This affects the keystone wallet adapter, but `wallet-adapter-wallets` is the common way to access all wallet adapters, and that has a dependency on keystone wallet adapter, and hence has this issue.

As you said, you can install from a specific wallet adapter as a workaround. But actually @ChetanXpro for Backpack, you don't need an adapter at all. Backpack implements wallet standard and will be picked up by all apps without needing to be listed. That's why that package is deprecated.

Most wallets now implement wallet standard and don't need to be imported and listed in wallets, which will hopefully make this less annoying to work around for now.

**Comment by ChetanXpro** [comment] 2024-03-01 18:45
Thank you @mcintyre94 for sharing the update, sure i will remove these adapters from my code.

**Comment by mcintyre94** [comment] 2024-03-02 13:00
I was hoping we could fix this for everyone, and I think it will be fixed for some package managers, but with that stackblitz repo (using plain npm) I needed to add an override to the app too to get it working.

So:

- First, try upgrading to `@solana/wallet-adapter-wallets@0.19.29`. This might fix it for you without you doing anything else
- If you still have the issue, you need to override `@ngraveio/bc-ur` to version `1.1.6`. Both 1.1.8 and 1.1.9 are broken. My stackblitz repo has the fix for npm: https://stackblitz.com/edit/nextjs-pksjhy?file=package.json . Other package managers you'll need to look up how to override a module

Hopefully `bc-ur` will publish a fixed version at some point and this problem will go away!

**Closed** 2024-03-04 16:10 UTC
